categories/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'categories'
urlpatterns = [
    path('categories/', views.category_list, name="list"),
    path('create/', views.create_category, name="create"),
    path('categories/<slug>', views.update_category, name="update"),
    path('delete/<slug>', views.delete_category, name="delete"),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('public/', include('pubproducts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
    path('list/', views.product_list, name="list"),
    path('make-product/', views.create_product, name="create"),
    path('create-product/<slug>', views.update_product, name="update"),
    path('delete-product/<slug>', views.delete_product, name="delete"),
]

pubproducts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'public'
urlpatterns = [
    path('list/', views.public_list, name="list"),
    path('list/<slug>', views.public_view, name="view"),
    path('lookup/<slug>', views.public_lookup, name="lookup"),
]

categories/models.py
from django.db import models

from email.policy import default
from turtle import title
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length=100, unique=True) #make the field unique
    # a slug to use as an identifier when editing and deleting
    slug = models.SlugField(default=None, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

products/models.py
from django.db import models

from email.policy import default
from turtle import title
from django.db import models
from django.contrib.auth.models import User
from categories import models as categories

class Product(models.Model):
    # make the field unique
    category = models.ForeignKey(categories.Category, default=None, on_delete=models.PROTECT)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.BigIntegerField()
    sku = models.BigIntegerField()
    picture = models.ImageField(default="default.png", blank=True)
    # a slug to use as an identifier when editing and deleting
    slug = models.SlugField(default=None, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

pubproducts/models.py
from django.db import models

# Create your models here.

categories/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Category
from django.contrib.auth.decorators import login_required
from . import create


def category_list(request):
    cats = Category.objects.all().order_by('date')
    return render(request, 'categories_list.html', {'cats': cats})

def create_category(request):
    if request.method == "POST":
        #if post from create form, then make the article with form values, else redirect back
        cat = create.CreateCategory(request.POST)
        if cat.is_valid():
            newCategory = cat.save(commit=False)
            newCategory.save()
            return redirect('categories:list')
    else:
        cat = create.CreateCategory(request.POST)
    return render(request, 'create_category.html', {'cat':cat})

def update_category(request, slug):
    cat = Category.objects.get(slug=slug)
    form = create.UpdateCategory(request.POST, instance=cat)
    if form.is_valid():
        form.save()
        return redirect('categories:list')
    return render(request, 'update_category.html', {'cat':cat, 'form':form})


def delete_category(request, slug):
    cat = Category.objects.get(slug=slug)
    cat.delete()
    return redirect('categories:list')

products/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Product
from django.contrib.auth.decorators import login_required
from . import crud

def product_list(request): #create collection from product model and serve it to the listing page for use
    products = Product.objects.all().order_by('date')
    return render(request, 'product_list.html', {'products': products})


def create_product(request):
    if request.method == "POST":
        #if post from create form, then make the article with form values, else redirect back
        product = crud.CreateProduct(request.POST, request.FILES)
        if product.is_valid():
            newProduct = product.save(commit=False)
            newProduct.save()
            return redirect('products:list')
    else:
        product = crud.CreateProduct(request.POST)
    return render(request, 'create_product.html', {'product': product})


def update_product(request, slug):
    product = Product.objects.get(slug=slug)
    form = crud.UpdateProduct(request.POST, request.FILES, instance=product) #by using instance can assign same slug
    if form.is_valid(): #check form validation
        form.save()
        return redirect('products:list')
    return render(request, 'update_product.html', {'product': product, 'form': form})


def delete_product(request, slug): #delete by finding the slug and remove all assosiated records
    product = Product.objects.get(slug=slug)
    product.delete()
    return redirect('products:list')

pubproducts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from products.models import Product

# create collection from product model and serve it to the listing page for use
def public_list(request):
    products = Product.objects.all().order_by('date')
    return render(request, 'all_products.html', {'products': products})


def public_view(request, slug):
    products = Product.objects.get(slug=slug)
    return render(request, 'product_view.html', {'products': products})


def public_lookup(request, slug):
    products = Product.objects.all(category=slug)
    return render(request, 'product_lookup.html', {'products': products})

categories/templates/categories_list.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
<h3 style="color:gray">
    <div class="jumbotron text-light">
        <h1 class="display-4" style="text-align: center;">Categories</h1>
        <p class="lead" style="text-align: center;">Create categories here</p>
        <a href="{% url 'categories:create' %}" class="btn btn-primary w-50" style="margin-left: 310px;">Create &#128270;</a>
        <hr class="my-4" style="color: rgb(251, 251, 251); height: 5px;">
    </div>
</h3>
<br/>
<div class="article">
    {% if user.is_superuser %}
        {%for category in cats%}
            <div class="card" style="width: 18rem; float: left; margin-right: 50px; margin-bottom: 20px; margin-left: 50px;">
                <div class="card-body">
                    <h5 class="card-title">{{category.title}}</h5>
                    <li class="list-group-item"><a href="{% url 'categories:update' slug=category.slug %}" class="btn btn-primary" style="width:100%" > Edit </a></li>
                    <li class="list-group-item"><a href="{% url 'categories:delete' slug=category.slug %}" class="btn btn-primary" style="width:100%">
                    Delete</a></li>
                </div>
            </div>
        {%endfor%}
    {% else %}
        <h1>You are not permitted to view this page</h1>
    {% endif %}
</div>
{%endblock%}

categories/templates/create_category.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
    {% if user.is_superuser %}
        <div class="create-article">
        <p class="lead text-white" style="text-align: center;">Create category</p>
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <form action="{% url 'categories:create' %}" method="post" class="justify-content-center">
                            <div class="form-group col-md-6">
                                {% csrf_token %}
                                {{cat}}
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
    {% else %}
        <h1>You are not permitted to view this page</h1>
    {% endif %}
{%endblock%}

categories/templates/update_category.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
<div class="create-article">
    {% if user.is_superuser %}
        <p class="lead text-white" style="text-align: center;">Editing {{cat}}</p>
        <div class="d-flex justify-content-center">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <form action="{% url 'categories:update' slug=cat.slug %}" method="post" class="justify-content-center">
                        <div class="form-group col-md-6">
                            {% csrf_token %}
                            {{form}}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <h1>You are not permitted to view this page</h1>
    {% endif %}
</div>
{%endblock%}

djangoproject/templates/private_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Public</title>
</head>
<body style="background-color: rgb(42, 42, 42);">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Django Shop by Tavis &#128722;</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'categories:list' %}">Categories List</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'products:list' %}">Product List </a>
                </li>
            </ul>
        </div>
    </nav>
    <br/>
    {% block content %}
    {% endblock %}
</body>
</html>

djangoproject/templates/pub_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Public</title>
</head>
<body style="background-color: rgb(42, 42, 42);">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Django Shop by Tavis &#128722;</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'public:list' %}">Product List <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
    <br/>
    {% block content %}
    {% endblock %}
</body>
</html>

products/templates/create_product.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
{% if user.is_superuser %}
<p class="lead text-white" style="text-align: center;">Create a product</p>
<div class="d-flex justify-content-center">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <form action="{% url 'products:create' %}" method="post" enctype="multipart/form-data" class="justify-content-center">
                <div class="form-group col-md-6">
                    {% csrf_token %}
                    {{product}}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% else %}
<h1>You are not permitted to view this page</h1>
{% endif %}
{%endblock%}

products/templates/product_list.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
<h3 style="color:gray">
    <div class="jumbotron text-light">
        <h1 class="display-4" style="text-align: center;">Products</h1>
        <p class="lead" style="text-align: center;">Add, edit and delete products</p>
        <a href="{% url 'products:create' %}" class="btn btn-primary w-50" style="margin-left: 325px;">Create
            &#128270;</a>
        <hr class="my-4" style="color: rgb(251, 251, 251); height: 5px;">
    </div>
</h3>
<br />
<div class="article">
    {% if user.is_superuser %}
        {%for product in products%}
            <div class="card" style="width: 18rem; float: left; margin-right: 50px; margin-bottom: 20px; margin-left: 50px;">
                <div class="card-body">
                    <img class="card-img-top img-thumbnail" src="{{product.picture.url}}" alt="Main image">
                    <h5 class="card-title">{{product.category}}</h5>
                    <h5 class="card-title">{{product.title}}</h5>
                    <p class="card-text">{{product.description}}</p>
                    <li class="list-group-item">${{product.price}}</li>
                    <li class="list-group-item">Quantity: {{product.quantity}}</li>
                    <li class="list-group-item">SKU: {{product.sku}}</li>
                    <li class="list-group-item"><a href="{% url 'products:update' slug=product.slug %}" class="btn btn-primary" style="width:100%">
                            Edit </a></li>
                    <li class="list-group-item"><a href="{% url 'products:delete' slug=product.slug %}" class="btn btn-primary" style="width:100%">
                            Delete</a></li>
                </div>
            </div>
        {%endfor%}
    {% else %}
        <h1>You are not permitted to view this page</h1>
    {% endif %}
</div>
{%endblock%}

products/templates/update_product.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
    {% if user.is_superuser %}
    <p class="lead text-white" style="text-align: center;">Edit product</p>
    <div class="d-flex justify-content-center">
        <div class="card" style="width: 30rem;">
            <div class="card-body">
                <form action="{% url 'products:update' slug=product.slug %}" method="post" enctype="multipart/form-data"
                    class="justify-content-center">
                    <div class="form-group col-md-6">
                        {% csrf_token %}
                        {{form}}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    {% else %}
        <h1>You are not permitted to view this page</h1>
    {% endif %}
</div>
{% endblock %}

pubproducts/templates/all_products.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\pub_layout.html' %}
{% block content %}   
   <h3 style="color:gray">
        <div class="jumbotron text-light">
            <h1 class="display-4" style="text-align: center;">Tavis Django &#128187;</h1>
            <p class="lead" style="text-align: center;">Here you can view all products available, as well as view them individually in detail by clicking their link</p>
            <hr class="my-4" style="color: rgb(251, 251, 251); height: 5px;">
        </div>
    </h3>
    <br />
    {%for product in products%}
        <div style="padding: 20px; width: 50%; margin-left: auto; margin-right: auto; box-sizing: content-box;">
            <table class="table table-striped table-bordered">
                <caption>Infomation on {{product.title}}</caption>
                <thead class="bg-light">
                    <tr>
                        <th scope="col">Category</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">SKU</th>
                        <th scope="col">Picture</th>
                    </tr>
                </thead>
                <tbody class="bg-light">
                    <tr>
                        <td>{{product.category}}</td>
                        <td>{{product.title}}</td>
                        <td>{{product.description}}</td>
                        <td>{{product.price}}</td>
                        <td>{{product.quantity}}</td>
                        <td>{{product.sku}}</td>
                        <td><img class="img-thumbnail" src="{{product.picture.url}}" /></td>
                        <a href="{% url 'public:view' slug=product.slug %}" class="btn btn-primary">View &#128270;</a>
                        <a href="{% url 'public:lookup' slug=product.category %}" class="btn btn-primary" style="float:right">Items in this category &#128196;</a>
                    </tr>
                </tbody>
            </table>
        </div>
    {% endfor %}
{%endblock%}

pubproducts/templates/product_view.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\pub_layout.html' %}
{% block content %}
    <h3 style="color:gray">
        <article class="text-light" style="text-align: center;">Viewing Product <strong>{{products.title}}</strong></article>
    </h3>
    <br/>
    <hr style="color: dodgerblue;"/>
        <div class="d-flex justify-content-center">
            <div class="card bg-primary" style="width: 18rem;">
                <img class="card-img-top img-thumbnail" src="{{products.picture.url}}" alt="Main image">
                <div class="card-body">
                    <h5 class="card-title">{{products.category}}</h5>
                    <hr/>
                    <h5 class="card-title">{{products.title}}</h5>
                    <hr />
                    <p class="card-text">{{products.description}}</p>
                    <li class="list-group-item">${{products.price}}</li>
                    <li class="list-group-item">Quantity: {{products.quantity}}</li>
                    <li class="list-group-item">#{{products.sku}}</li>
                </div>
            </div>
        </div>
{% endblock %}

pubproducts/templates/products_lookup.html
{% extends 'C:\\Users\\Tavis\\Documents\\djangoproject\\djangoproject\\templates\\private_layout.html' %}
{% block content %}
<h3 style="color:gray">
    <div class="jumbotron text-light">
        <h1 class="display-4" style="text-align: center;">Items in ...</h1>
        <p class="lead" style="text-align: center;">Veiwing a list of items!</p>
        <hr class="my-4" style="color: rgb(251, 251, 251); height: 5px;">
    </div>
</h3>
<br/>
<div class="article">
    {%for product in products%}
        <div class="card" style="width: 18rem; float: left; margin-right: 50px; margin-bottom: 20px; margin-left: 50px;">
            <div class="card-body">
                <h5 class="card-title">{{product.title}}</h5>
            </div>
        </div>
    {%endfor%}
</div>
{%endblock%}